import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import toast from "react-hot-toast";

interface TwoFactorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  apiFetch: (url: string, options?: any) => Promise<any>;
}

export function TwoFactorModal({ isOpen, onClose, onSuccess, apiFetch }: TwoFactorModalProps) {
  const [step, setStep] = useState<1 | 2>(1); // 1: Show QR, 2: Loading/Done
  const [qrCodeUrl, setQrCodeUrl] = useState("");
  const [secret, setSecret] = useState("");
  const [token, setToken] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const setupStarted = React.useRef(false);

  useEffect(() => {
    if (isOpen) {
      if (!setupStarted.current) {
        setupStarted.current = true;
        setup2FA();
      }
    } else {
      setupStarted.current = false;
    }
  }, [isOpen]);

  const setup2FA = async () => {
    setIsLoading(true);
    try {
      const res = await apiFetch("/api/auth/2fa/setup", { method: "POST" });
      if (res.ok) {
        const data = await res.json();
        setQrCodeUrl(data.qrCodeUrl);
        setSecret(data.secret);
        setStep(1);
      } else {
        const errorData = await res.json().catch(() => ({}));
        console.error("Setup 2FA Failed:", errorData);
        toast.error("Failed to setup 2FA");
        onClose();
      }
    } catch (err) {
      toast.error("Network error");
      onClose();
    } finally {
      setIsLoading(false);
    }
  };

  const handleVerify = async () => {
    if (token.length !== 6) return toast.error("Enter a valid 6-digit code");
    setIsLoading(true);
    try {
      const res = await apiFetch("/api/auth/2fa/verify", {
        method: "POST",
        body: JSON.stringify({ token })
      });
      if (res.ok) {
        toast.success("2FA enabled successfully!");
        onSuccess();
        onClose();
      } else {
        const data = await res.json();
        toast.error(data.error || "Invalid code");
      }
    } catch (err) {
      toast.error("Network error");
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white dark:bg-slate-900 rounded-xl p-6 w-full max-w-md shadow-xl border border-gray-200 dark:border-slate-800">
        <h2 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">Enable 2FA (Authenticator App)</h2>

        {step === 1 && (
          <div className="space-y-4">
            <p className="text-sm text-gray-600 dark:text-gray-400">
              1. Install an authenticator app (e.g. Google Authenticator, Authy).
            </p>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              2. Scan the QR code below.
            </p>

            {isLoading ? (
              <div className="flex justify-center p-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 dark:border-blue-400"></div>
              </div>
            ) : qrCodeUrl ? (
              <div className="flex flex-col items-center gap-2">
                <img src={qrCodeUrl} alt="QR Code" className="w-48 h-48 border rounded-xl" />
                <p className="text-xs text-gray-500 font-mono mt-2 bg-gray-100 dark:bg-slate-800 px-2 py-1 rounded">
                  {secret}
                </p>
              </div>
            ) : null}

            <div className="pt-2 border-t border-gray-100 dark:border-slate-800">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                3. Enter the 6-digit code generated by the app.
              </p>
              <Input
                type="text"
                placeholder="000000"
                maxLength={6}
                value={token}
                onChange={e => setToken(e.target.value)}
              />
            </div>

            <div className="flex justify-end gap-2 mt-4">
              <Button variant="outline" onClick={onClose} disabled={isLoading}>Cancel</Button>
              <Button onClick={handleVerify} isLoading={isLoading}>Verify & Enable</Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
